//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_cancel_all_goalResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_cancel_all_goal";
        public override string RosMessageName => k_RosMessageName;

        // response
        public bool success;

        public srv_cancel_all_goalResponse()
        {
            this.success = false;
        }

        public srv_cancel_all_goalResponse(bool success)
        {
            this.success = success;
        }

        public static srv_cancel_all_goalResponse Deserialize(MessageDeserializer deserializer) => new srv_cancel_all_goalResponse(deserializer);

        private srv_cancel_all_goalResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "srv_cancel_all_goalResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
