//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_ardock_scanRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_ardock_scan";
        public override string RosMessageName => k_RosMessageName;

        // goal request definition
        public bool enable_ardock_scan;
        public bool is_scan_exposures;

        public srv_ardock_scanRequest()
        {
            this.enable_ardock_scan = false;
            this.is_scan_exposures = false;
        }

        public srv_ardock_scanRequest(bool enable_ardock_scan, bool is_scan_exposures)
        {
            this.enable_ardock_scan = enable_ardock_scan;
            this.is_scan_exposures = is_scan_exposures;
        }

        public static srv_ardock_scanRequest Deserialize(MessageDeserializer deserializer) => new srv_ardock_scanRequest(deserializer);

        private srv_ardock_scanRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enable_ardock_scan);
            deserializer.Read(out this.is_scan_exposures);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enable_ardock_scan);
            serializer.Write(this.is_scan_exposures);
        }

        public override string ToString()
        {
            return "srv_ardock_scanRequest: " +
            "\nenable_ardock_scan: " + enable_ardock_scan.ToString() +
            "\nis_scan_exposures: " + is_scan_exposures.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
