//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_enable_sensor_streamRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_enable_sensor_stream";
        public override string RosMessageName => k_RosMessageName;

        public bool stream_enable;
        // master switch: true - allow to config streams, fail: turn all stream off
        public bool enable_set_tbcore;
        public bool tbcore;
        public bool enable_set_servo_neck;
        public bool servo_neck;
        public bool enable_set_wheel_encoder;
        public bool wheel_encoder;
        public bool enable_set_servo_ext1;
        public bool servo_ext1;
        public bool enable_set_servo_ext2;
        public bool servo_ext2;

        public srv_enable_sensor_streamRequest()
        {
            this.stream_enable = false;
            this.enable_set_tbcore = false;
            this.tbcore = false;
            this.enable_set_servo_neck = false;
            this.servo_neck = false;
            this.enable_set_wheel_encoder = false;
            this.wheel_encoder = false;
            this.enable_set_servo_ext1 = false;
            this.servo_ext1 = false;
            this.enable_set_servo_ext2 = false;
            this.servo_ext2 = false;
        }

        public srv_enable_sensor_streamRequest(bool stream_enable, bool enable_set_tbcore, bool tbcore, bool enable_set_servo_neck, bool servo_neck, bool enable_set_wheel_encoder, bool wheel_encoder, bool enable_set_servo_ext1, bool servo_ext1, bool enable_set_servo_ext2, bool servo_ext2)
        {
            this.stream_enable = stream_enable;
            this.enable_set_tbcore = enable_set_tbcore;
            this.tbcore = tbcore;
            this.enable_set_servo_neck = enable_set_servo_neck;
            this.servo_neck = servo_neck;
            this.enable_set_wheel_encoder = enable_set_wheel_encoder;
            this.wheel_encoder = wheel_encoder;
            this.enable_set_servo_ext1 = enable_set_servo_ext1;
            this.servo_ext1 = servo_ext1;
            this.enable_set_servo_ext2 = enable_set_servo_ext2;
            this.servo_ext2 = servo_ext2;
        }

        public static srv_enable_sensor_streamRequest Deserialize(MessageDeserializer deserializer) => new srv_enable_sensor_streamRequest(deserializer);

        private srv_enable_sensor_streamRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stream_enable);
            deserializer.Read(out this.enable_set_tbcore);
            deserializer.Read(out this.tbcore);
            deserializer.Read(out this.enable_set_servo_neck);
            deserializer.Read(out this.servo_neck);
            deserializer.Read(out this.enable_set_wheel_encoder);
            deserializer.Read(out this.wheel_encoder);
            deserializer.Read(out this.enable_set_servo_ext1);
            deserializer.Read(out this.servo_ext1);
            deserializer.Read(out this.enable_set_servo_ext2);
            deserializer.Read(out this.servo_ext2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stream_enable);
            serializer.Write(this.enable_set_tbcore);
            serializer.Write(this.tbcore);
            serializer.Write(this.enable_set_servo_neck);
            serializer.Write(this.servo_neck);
            serializer.Write(this.enable_set_wheel_encoder);
            serializer.Write(this.wheel_encoder);
            serializer.Write(this.enable_set_servo_ext1);
            serializer.Write(this.servo_ext1);
            serializer.Write(this.enable_set_servo_ext2);
            serializer.Write(this.servo_ext2);
        }

        public override string ToString()
        {
            return "srv_enable_sensor_streamRequest: " +
            "\nstream_enable: " + stream_enable.ToString() +
            "\nenable_set_tbcore: " + enable_set_tbcore.ToString() +
            "\ntbcore: " + tbcore.ToString() +
            "\nenable_set_servo_neck: " + enable_set_servo_neck.ToString() +
            "\nservo_neck: " + servo_neck.ToString() +
            "\nenable_set_wheel_encoder: " + enable_set_wheel_encoder.ToString() +
            "\nwheel_encoder: " + wheel_encoder.ToString() +
            "\nenable_set_servo_ext1: " + enable_set_servo_ext1.ToString() +
            "\nservo_ext1: " + servo_ext1.ToString() +
            "\nenable_set_servo_ext2: " + enable_set_servo_ext2.ToString() +
            "\nservo_ext2: " + servo_ext2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
