//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_get_servo_infoRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_get_servo_info";
        public override string RosMessageName => k_RosMessageName;

        public byte sid;

        public srv_get_servo_infoRequest()
        {
            this.sid = 0;
        }

        public srv_get_servo_infoRequest(byte sid)
        {
            this.sid = sid;
        }

        public static srv_get_servo_infoRequest Deserialize(MessageDeserializer deserializer) => new srv_get_servo_infoRequest(deserializer);

        private srv_get_servo_infoRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sid);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sid);
        }

        public override string ToString()
        {
            return "srv_get_servo_infoRequest: " +
            "\nsid: " + sid.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
