//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_servo_write_eepRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_servo_write_eep";
        public override string RosMessageName => k_RosMessageName;

        public byte sid;
        public byte address;
        // the memory at this address could be 2 bytes or 1 byte
        public bool is_2bytes_address;
        public ushort value;

        public srv_servo_write_eepRequest()
        {
            this.sid = 0;
            this.address = 0;
            this.is_2bytes_address = false;
            this.value = 0;
        }

        public srv_servo_write_eepRequest(byte sid, byte address, bool is_2bytes_address, ushort value)
        {
            this.sid = sid;
            this.address = address;
            this.is_2bytes_address = is_2bytes_address;
            this.value = value;
        }

        public static srv_servo_write_eepRequest Deserialize(MessageDeserializer deserializer) => new srv_servo_write_eepRequest(deserializer);

        private srv_servo_write_eepRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sid);
            deserializer.Read(out this.address);
            deserializer.Read(out this.is_2bytes_address);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sid);
            serializer.Write(this.address);
            serializer.Write(this.is_2bytes_address);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "srv_servo_write_eepRequest: " +
            "\nsid: " + sid.ToString() +
            "\naddress: " + address.ToString() +
            "\nis_2bytes_address: " + is_2bytes_address.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
