//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_connectResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_connect";
        public override string RosMessageName => k_RosMessageName;

        public bool is_connected;
        public string port_name;

        public srv_connectResponse()
        {
            this.is_connected = false;
            this.port_name = "";
        }

        public srv_connectResponse(bool is_connected, string port_name)
        {
            this.is_connected = is_connected;
            this.port_name = port_name;
        }

        public static srv_connectResponse Deserialize(MessageDeserializer deserializer) => new srv_connectResponse(deserializer);

        private srv_connectResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.is_connected);
            deserializer.Read(out this.port_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.is_connected);
            serializer.Write(this.port_name);
        }

        public override string ToString()
        {
            return "srv_connectResponse: " +
            "\nis_connected: " + is_connected.ToString() +
            "\nport_name: " + port_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
