//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_connect_portsResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_connect_ports";
        public override string RosMessageName => k_RosMessageName;

        public string[] connect_ports;

        public srv_connect_portsResponse()
        {
            this.connect_ports = new string[0];
        }

        public srv_connect_portsResponse(string[] connect_ports)
        {
            this.connect_ports = connect_ports;
        }

        public static srv_connect_portsResponse Deserialize(MessageDeserializer deserializer) => new srv_connect_portsResponse(deserializer);

        private srv_connect_portsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.connect_ports, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.connect_ports);
            serializer.Write(this.connect_ports);
        }

        public override string ToString()
        {
            return "srv_connect_portsResponse: " +
            "\nconnect_ports: " + System.String.Join(", ", connect_ports.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
