//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_ardock_calib_feedbackResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_ardock_calib_feedback";
        public override string RosMessageName => k_RosMessageName;

        // response
        public int calib_state;
        // kIdle = -1
        // kIsRunning =0
        // kFail = 1
        // kSuccess = 2

        public srv_ardock_calib_feedbackResponse()
        {
            this.calib_state = 0;
        }

        public srv_ardock_calib_feedbackResponse(int calib_state)
        {
            this.calib_state = calib_state;
        }

        public static srv_ardock_calib_feedbackResponse Deserialize(MessageDeserializer deserializer) => new srv_ardock_calib_feedbackResponse(deserializer);

        private srv_ardock_calib_feedbackResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.calib_state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.calib_state);
        }

        public override string ToString()
        {
            return "srv_ardock_calib_feedbackResponse: " +
            "\ncalib_state: " + calib_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
