//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_vo_resetResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_vo_reset";
        public override string RosMessageName => k_RosMessageName;

        public bool result;

        public srv_vo_resetResponse()
        {
            this.result = false;
        }

        public srv_vo_resetResponse(bool result)
        {
            this.result = result;
        }

        public static srv_vo_resetResponse Deserialize(MessageDeserializer deserializer) => new srv_vo_resetResponse(deserializer);

        private srv_vo_resetResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "srv_vo_resetResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
