//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_debug_pid_streamResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_debug_pid_stream";
        public override string RosMessageName => k_RosMessageName;

        public bool stream_enable;

        public srv_debug_pid_streamResponse()
        {
            this.stream_enable = false;
        }

        public srv_debug_pid_streamResponse(bool stream_enable)
        {
            this.stream_enable = stream_enable;
        }

        public static srv_debug_pid_streamResponse Deserialize(MessageDeserializer deserializer) => new srv_debug_pid_streamResponse(deserializer);

        private srv_debug_pid_streamResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stream_enable);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stream_enable);
        }

        public override string ToString()
        {
            return "srv_debug_pid_streamResponse: " +
            "\nstream_enable: " + stream_enable.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
