//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_debug_change_pose_goalRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_debug_change_pose_goal";
        public override string RosMessageName => k_RosMessageName;

        // goal request definition
        public string frame_id;
        public double x;
        public double y;
        public double yaw;
        public double dx;
        public double dy;
        public double dyaw;

        public srv_debug_change_pose_goalRequest()
        {
            this.frame_id = "";
            this.x = 0.0;
            this.y = 0.0;
            this.yaw = 0.0;
            this.dx = 0.0;
            this.dy = 0.0;
            this.dyaw = 0.0;
        }

        public srv_debug_change_pose_goalRequest(string frame_id, double x, double y, double yaw, double dx, double dy, double dyaw)
        {
            this.frame_id = frame_id;
            this.x = x;
            this.y = y;
            this.yaw = yaw;
            this.dx = dx;
            this.dy = dy;
            this.dyaw = dyaw;
        }

        public static srv_debug_change_pose_goalRequest Deserialize(MessageDeserializer deserializer) => new srv_debug_change_pose_goalRequest(deserializer);

        private srv_debug_change_pose_goalRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frame_id);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.yaw);
            deserializer.Read(out this.dx);
            deserializer.Read(out this.dy);
            deserializer.Read(out this.dyaw);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frame_id);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.yaw);
            serializer.Write(this.dx);
            serializer.Write(this.dy);
            serializer.Write(this.dyaw);
        }

        public override string ToString()
        {
            return "srv_debug_change_pose_goalRequest: " +
            "\nframe_id: " + frame_id.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\ndx: " + dx.ToString() +
            "\ndy: " + dy.ToString() +
            "\ndyaw: " + dyaw.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
