//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_set_servo_zero_offsetResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_set_servo_zero_offset";
        public override string RosMessageName => k_RosMessageName;

        public double current_servo_offset_raw;

        public srv_set_servo_zero_offsetResponse()
        {
            this.current_servo_offset_raw = 0.0;
        }

        public srv_set_servo_zero_offsetResponse(double current_servo_offset_raw)
        {
            this.current_servo_offset_raw = current_servo_offset_raw;
        }

        public static srv_set_servo_zero_offsetResponse Deserialize(MessageDeserializer deserializer) => new srv_set_servo_zero_offsetResponse(deserializer);

        private srv_set_servo_zero_offsetResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_servo_offset_raw);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_servo_offset_raw);
        }

        public override string ToString()
        {
            return "srv_set_servo_zero_offsetResponse: " +
            "\ncurrent_servo_offset_raw: " + current_servo_offset_raw.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
