//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_recalibRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_recalib";
        public override string RosMessageName => k_RosMessageName;

        public bool enable_recalib;

        public srv_recalibRequest()
        {
            this.enable_recalib = false;
        }

        public srv_recalibRequest(bool enable_recalib)
        {
            this.enable_recalib = enable_recalib;
        }

        public static srv_recalibRequest Deserialize(MessageDeserializer deserializer) => new srv_recalibRequest(deserializer);

        private srv_recalibRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enable_recalib);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enable_recalib);
        }

        public override string ToString()
        {
            return "srv_recalibRequest: " +
            "\nenable_recalib: " + enable_recalib.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
