//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_ardock_camera_controlRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_ardock_camera_control";
        public override string RosMessageName => k_RosMessageName;

        // goal request definition
        public bool enable_set_exposure;
        public int default_exposure;

        public srv_ardock_camera_controlRequest()
        {
            this.enable_set_exposure = false;
            this.default_exposure = 0;
        }

        public srv_ardock_camera_controlRequest(bool enable_set_exposure, int default_exposure)
        {
            this.enable_set_exposure = enable_set_exposure;
            this.default_exposure = default_exposure;
        }

        public static srv_ardock_camera_controlRequest Deserialize(MessageDeserializer deserializer) => new srv_ardock_camera_controlRequest(deserializer);

        private srv_ardock_camera_controlRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enable_set_exposure);
            deserializer.Read(out this.default_exposure);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enable_set_exposure);
            serializer.Write(this.default_exposure);
        }

        public override string ToString()
        {
            return "srv_ardock_camera_controlRequest: " +
            "\nenable_set_exposure: " + enable_set_exposure.ToString() +
            "\ndefault_exposure: " + default_exposure.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
