//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_set_pose_controllerResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_set_pose_controller";
        public override string RosMessageName => k_RosMessageName;

        // response
        public double k_d;
        public double k_yaw_small_angle;
        public double max_linear_vel;
        public double max_angular_vel;

        public srv_set_pose_controllerResponse()
        {
            this.k_d = 0.0;
            this.k_yaw_small_angle = 0.0;
            this.max_linear_vel = 0.0;
            this.max_angular_vel = 0.0;
        }

        public srv_set_pose_controllerResponse(double k_d, double k_yaw_small_angle, double max_linear_vel, double max_angular_vel)
        {
            this.k_d = k_d;
            this.k_yaw_small_angle = k_yaw_small_angle;
            this.max_linear_vel = max_linear_vel;
            this.max_angular_vel = max_angular_vel;
        }

        public static srv_set_pose_controllerResponse Deserialize(MessageDeserializer deserializer) => new srv_set_pose_controllerResponse(deserializer);

        private srv_set_pose_controllerResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.k_d);
            deserializer.Read(out this.k_yaw_small_angle);
            deserializer.Read(out this.max_linear_vel);
            deserializer.Read(out this.max_angular_vel);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.k_d);
            serializer.Write(this.k_yaw_small_angle);
            serializer.Write(this.max_linear_vel);
            serializer.Write(this.max_angular_vel);
        }

        public override string ToString()
        {
            return "srv_set_pose_controllerResponse: " +
            "\nk_d: " + k_d.ToString() +
            "\nk_yaw_small_angle: " + k_yaw_small_angle.ToString() +
            "\nmax_linear_vel: " + max_linear_vel.ToString() +
            "\nmax_angular_vel: " + max_angular_vel.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
