//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_set_pidRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_set_pid";
        public override string RosMessageName => k_RosMessageName;

        public long pid_id;
        public bool enable_set_p;
        public bool enable_set_i;
        public bool enable_set_d;
        public bool enable_set_setpoint;
        public double p_value;
        public double i_value;
        public double d_value;
        public double setpoint;

        public srv_set_pidRequest()
        {
            this.pid_id = 0;
            this.enable_set_p = false;
            this.enable_set_i = false;
            this.enable_set_d = false;
            this.enable_set_setpoint = false;
            this.p_value = 0.0;
            this.i_value = 0.0;
            this.d_value = 0.0;
            this.setpoint = 0.0;
        }

        public srv_set_pidRequest(long pid_id, bool enable_set_p, bool enable_set_i, bool enable_set_d, bool enable_set_setpoint, double p_value, double i_value, double d_value, double setpoint)
        {
            this.pid_id = pid_id;
            this.enable_set_p = enable_set_p;
            this.enable_set_i = enable_set_i;
            this.enable_set_d = enable_set_d;
            this.enable_set_setpoint = enable_set_setpoint;
            this.p_value = p_value;
            this.i_value = i_value;
            this.d_value = d_value;
            this.setpoint = setpoint;
        }

        public static srv_set_pidRequest Deserialize(MessageDeserializer deserializer) => new srv_set_pidRequest(deserializer);

        private srv_set_pidRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pid_id);
            deserializer.Read(out this.enable_set_p);
            deserializer.Read(out this.enable_set_i);
            deserializer.Read(out this.enable_set_d);
            deserializer.Read(out this.enable_set_setpoint);
            deserializer.Read(out this.p_value);
            deserializer.Read(out this.i_value);
            deserializer.Read(out this.d_value);
            deserializer.Read(out this.setpoint);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pid_id);
            serializer.Write(this.enable_set_p);
            serializer.Write(this.enable_set_i);
            serializer.Write(this.enable_set_d);
            serializer.Write(this.enable_set_setpoint);
            serializer.Write(this.p_value);
            serializer.Write(this.i_value);
            serializer.Write(this.d_value);
            serializer.Write(this.setpoint);
        }

        public override string ToString()
        {
            return "srv_set_pidRequest: " +
            "\npid_id: " + pid_id.ToString() +
            "\nenable_set_p: " + enable_set_p.ToString() +
            "\nenable_set_i: " + enable_set_i.ToString() +
            "\nenable_set_d: " + enable_set_d.ToString() +
            "\nenable_set_setpoint: " + enable_set_setpoint.ToString() +
            "\np_value: " + p_value.ToString() +
            "\ni_value: " + i_value.ToString() +
            "\nd_value: " + d_value.ToString() +
            "\nsetpoint: " + setpoint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
