//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_connect_portsRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_connect_ports";
        public override string RosMessageName => k_RosMessageName;


        public srv_connect_portsRequest()
        {
        }
        public static srv_connect_portsRequest Deserialize(MessageDeserializer deserializer) => new srv_connect_portsRequest(deserializer);

        private srv_connect_portsRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "srv_connect_portsRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
