//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_set_servo_posRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_set_servo_pos";
        public override string RosMessageName => k_RosMessageName;

        public byte sid;
        public bool use_rad;
        public ushort pos_raw;
        public double pos_rad;
        // torque control mode:
        // kBreak = 0,
        // kOn = 1,
        // kFree = 2
        public byte torque;
        public byte playtime;

        public srv_set_servo_posRequest()
        {
            this.sid = 0;
            this.use_rad = false;
            this.pos_raw = 0;
            this.pos_rad = 0.0;
            this.torque = 0;
            this.playtime = 0;
        }

        public srv_set_servo_posRequest(byte sid, bool use_rad, ushort pos_raw, double pos_rad, byte torque, byte playtime)
        {
            this.sid = sid;
            this.use_rad = use_rad;
            this.pos_raw = pos_raw;
            this.pos_rad = pos_rad;
            this.torque = torque;
            this.playtime = playtime;
        }

        public static srv_set_servo_posRequest Deserialize(MessageDeserializer deserializer) => new srv_set_servo_posRequest(deserializer);

        private srv_set_servo_posRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sid);
            deserializer.Read(out this.use_rad);
            deserializer.Read(out this.pos_raw);
            deserializer.Read(out this.pos_rad);
            deserializer.Read(out this.torque);
            deserializer.Read(out this.playtime);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sid);
            serializer.Write(this.use_rad);
            serializer.Write(this.pos_raw);
            serializer.Write(this.pos_rad);
            serializer.Write(this.torque);
            serializer.Write(this.playtime);
        }

        public override string ToString()
        {
            return "srv_set_servo_posRequest: " +
            "\nsid: " + sid.ToString() +
            "\nuse_rad: " + use_rad.ToString() +
            "\npos_raw: " + pos_raw.ToString() +
            "\npos_rad: " + pos_rad.ToString() +
            "\ntorque: " + torque.ToString() +
            "\nplaytime: " + playtime.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
