//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_set_pose_controllerRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_set_pose_controller";
        public override string RosMessageName => k_RosMessageName;

        // goal request definition
        public bool enable_kyaw;
        // 0.0 -> 5.0
        public bool enable_kd;
        // 
        public bool enable_linear;
        // 0.0 -> 0.5
        public bool enable_angular;
        // 0.0 -> 1.5
        public double k_d;
        public double k_yaw_small_angle;
        public double max_linear_vel;
        public double max_angular_vel;

        public srv_set_pose_controllerRequest()
        {
            this.enable_kyaw = false;
            this.enable_kd = false;
            this.enable_linear = false;
            this.enable_angular = false;
            this.k_d = 0.0;
            this.k_yaw_small_angle = 0.0;
            this.max_linear_vel = 0.0;
            this.max_angular_vel = 0.0;
        }

        public srv_set_pose_controllerRequest(bool enable_kyaw, bool enable_kd, bool enable_linear, bool enable_angular, double k_d, double k_yaw_small_angle, double max_linear_vel, double max_angular_vel)
        {
            this.enable_kyaw = enable_kyaw;
            this.enable_kd = enable_kd;
            this.enable_linear = enable_linear;
            this.enable_angular = enable_angular;
            this.k_d = k_d;
            this.k_yaw_small_angle = k_yaw_small_angle;
            this.max_linear_vel = max_linear_vel;
            this.max_angular_vel = max_angular_vel;
        }

        public static srv_set_pose_controllerRequest Deserialize(MessageDeserializer deserializer) => new srv_set_pose_controllerRequest(deserializer);

        private srv_set_pose_controllerRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enable_kyaw);
            deserializer.Read(out this.enable_kd);
            deserializer.Read(out this.enable_linear);
            deserializer.Read(out this.enable_angular);
            deserializer.Read(out this.k_d);
            deserializer.Read(out this.k_yaw_small_angle);
            deserializer.Read(out this.max_linear_vel);
            deserializer.Read(out this.max_angular_vel);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enable_kyaw);
            serializer.Write(this.enable_kd);
            serializer.Write(this.enable_linear);
            serializer.Write(this.enable_angular);
            serializer.Write(this.k_d);
            serializer.Write(this.k_yaw_small_angle);
            serializer.Write(this.max_linear_vel);
            serializer.Write(this.max_angular_vel);
        }

        public override string ToString()
        {
            return "srv_set_pose_controllerRequest: " +
            "\nenable_kyaw: " + enable_kyaw.ToString() +
            "\nenable_kd: " + enable_kd.ToString() +
            "\nenable_linear: " + enable_linear.ToString() +
            "\nenable_angular: " + enable_angular.ToString() +
            "\nk_d: " + k_d.ToString() +
            "\nk_yaw_small_angle: " + k_yaw_small_angle.ToString() +
            "\nmax_linear_vel: " + max_linear_vel.ToString() +
            "\nmax_angular_vel: " + max_angular_vel.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
