//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_connectRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_connect";
        public override string RosMessageName => k_RosMessageName;

        public bool connect;
        public string port_name;

        public srv_connectRequest()
        {
            this.connect = false;
            this.port_name = "";
        }

        public srv_connectRequest(bool connect, string port_name)
        {
            this.connect = connect;
            this.port_name = port_name;
        }

        public static srv_connectRequest Deserialize(MessageDeserializer deserializer) => new srv_connectRequest(deserializer);

        private srv_connectRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.connect);
            deserializer.Read(out this.port_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.connect);
            serializer.Write(this.port_name);
        }

        public override string ToString()
        {
            return "srv_connectRequest: " +
            "\nconnect: " + connect.ToString() +
            "\nport_name: " + port_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
