//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_debug_change_pose_goalResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_debug_change_pose_goal";
        public override string RosMessageName => k_RosMessageName;

        // response
        public bool success;
        public int state_code;

        public srv_debug_change_pose_goalResponse()
        {
            this.success = false;
            this.state_code = 0;
        }

        public srv_debug_change_pose_goalResponse(bool success, int state_code)
        {
            this.success = success;
            this.state_code = state_code;
        }

        public static srv_debug_change_pose_goalResponse Deserialize(MessageDeserializer deserializer) => new srv_debug_change_pose_goalResponse(deserializer);

        private srv_debug_change_pose_goalResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.state_code);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.state_code);
        }

        public override string ToString()
        {
            return "srv_debug_change_pose_goalResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nstate_code: " + state_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
