//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_query_tbcoreResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_query_tbcore";
        public override string RosMessageName => k_RosMessageName;

        // response
        public bool success;

        public srv_query_tbcoreResponse()
        {
            this.success = false;
        }

        public srv_query_tbcoreResponse(bool success)
        {
            this.success = success;
        }

        public static srv_query_tbcoreResponse Deserialize(MessageDeserializer deserializer) => new srv_query_tbcoreResponse(deserializer);

        private srv_query_tbcoreResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "srv_query_tbcoreResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
