//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_ardock_camera_controlResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_ardock_camera_control";
        public override string RosMessageName => k_RosMessageName;

        // response
        public int default_exposure;

        public srv_ardock_camera_controlResponse()
        {
            this.default_exposure = 0;
        }

        public srv_ardock_camera_controlResponse(int default_exposure)
        {
            this.default_exposure = default_exposure;
        }

        public static srv_ardock_camera_controlResponse Deserialize(MessageDeserializer deserializer) => new srv_ardock_camera_controlResponse(deserializer);

        private srv_ardock_camera_controlResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.default_exposure);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.default_exposure);
        }

        public override string ToString()
        {
            return "srv_ardock_camera_controlResponse: " +
            "\ndefault_exposure: " + default_exposure.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
