//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_debug_pid_streamRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_debug_pid_stream";
        public override string RosMessageName => k_RosMessageName;

        public bool stream_enable;
        public long pid_id;

        public srv_debug_pid_streamRequest()
        {
            this.stream_enable = false;
            this.pid_id = 0;
        }

        public srv_debug_pid_streamRequest(bool stream_enable, long pid_id)
        {
            this.stream_enable = stream_enable;
            this.pid_id = pid_id;
        }

        public static srv_debug_pid_streamRequest Deserialize(MessageDeserializer deserializer) => new srv_debug_pid_streamRequest(deserializer);

        private srv_debug_pid_streamRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stream_enable);
            deserializer.Read(out this.pid_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stream_enable);
            serializer.Write(this.pid_id);
        }

        public override string ToString()
        {
            return "srv_debug_pid_streamRequest: " +
            "\nstream_enable: " + stream_enable.ToString() +
            "\npid_id: " + pid_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
