//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_reset_wheel_odometryResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_reset_wheel_odometry";
        public override string RosMessageName => k_RosMessageName;


        public srv_reset_wheel_odometryResponse()
        {
        }
        public static srv_reset_wheel_odometryResponse Deserialize(MessageDeserializer deserializer) => new srv_reset_wheel_odometryResponse(deserializer);

        private srv_reset_wheel_odometryResponse(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "srv_reset_wheel_odometryResponse: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
