//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_ardock_calib_feedbackRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_ardock_calib_feedback";
        public override string RosMessageName => k_RosMessageName;

        // goal request definition

        public srv_ardock_calib_feedbackRequest()
        {
        }
        public static srv_ardock_calib_feedbackRequest Deserialize(MessageDeserializer deserializer) => new srv_ardock_calib_feedbackRequest(deserializer);

        private srv_ardock_calib_feedbackRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "srv_ardock_calib_feedbackRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
