//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_autodockRequest : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_autodock";
        public override string RosMessageName => k_RosMessageName;

        // goal request definition
        public bool enable_autodock;

        public srv_autodockRequest()
        {
            this.enable_autodock = false;
        }

        public srv_autodockRequest(bool enable_autodock)
        {
            this.enable_autodock = enable_autodock;
        }

        public static srv_autodockRequest Deserialize(MessageDeserializer deserializer) => new srv_autodockRequest(deserializer);

        private srv_autodockRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enable_autodock);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enable_autodock);
        }

        public override string ToString()
        {
            return "srv_autodockRequest: " +
            "\nenable_autodock: " + enable_autodock.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
