//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class srv_ardock_scanResponse : Message
    {
        public const string k_RosMessageName = "tb_msgs/srv_ardock_scan";
        public override string RosMessageName => k_RosMessageName;

        // response
        public bool success;

        public srv_ardock_scanResponse()
        {
            this.success = false;
        }

        public srv_ardock_scanResponse(bool success)
        {
            this.success = success;
        }

        public static srv_ardock_scanResponse Deserialize(MessageDeserializer deserializer) => new srv_ardock_scanResponse(deserializer);

        private srv_ardock_scanResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "srv_ardock_scanResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
