//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class Cmd_motor_pwmMsg : Message
    {
        public const string k_RosMessageName = "tb_msgs/cmd_motor_pwm";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        // Set PWM value for each motor from -1000 to 1000
        //  motor_i_enable:
        //    true: set PWM = motor_i value
        //    false: set PWM = 0
        public bool motor_1_enable;
        public double pwm_motor_1;
        public ushort baseoffset_1;
        public bool motor_2_enable;
        public double pwm_motor_2;
        public ushort baseoffset_2;

        public Cmd_motor_pwmMsg()
        {
            this.header = new HeaderMsg();
            this.motor_1_enable = false;
            this.pwm_motor_1 = 0.0;
            this.baseoffset_1 = 0;
            this.motor_2_enable = false;
            this.pwm_motor_2 = 0.0;
            this.baseoffset_2 = 0;
        }

        public Cmd_motor_pwmMsg(HeaderMsg header, bool motor_1_enable, double pwm_motor_1, ushort baseoffset_1, bool motor_2_enable, double pwm_motor_2, ushort baseoffset_2)
        {
            this.header = header;
            this.motor_1_enable = motor_1_enable;
            this.pwm_motor_1 = pwm_motor_1;
            this.baseoffset_1 = baseoffset_1;
            this.motor_2_enable = motor_2_enable;
            this.pwm_motor_2 = pwm_motor_2;
            this.baseoffset_2 = baseoffset_2;
        }

        public static Cmd_motor_pwmMsg Deserialize(MessageDeserializer deserializer) => new Cmd_motor_pwmMsg(deserializer);

        private Cmd_motor_pwmMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.motor_1_enable);
            deserializer.Read(out this.pwm_motor_1);
            deserializer.Read(out this.baseoffset_1);
            deserializer.Read(out this.motor_2_enable);
            deserializer.Read(out this.pwm_motor_2);
            deserializer.Read(out this.baseoffset_2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.motor_1_enable);
            serializer.Write(this.pwm_motor_1);
            serializer.Write(this.baseoffset_1);
            serializer.Write(this.motor_2_enable);
            serializer.Write(this.pwm_motor_2);
            serializer.Write(this.baseoffset_2);
        }

        public override string ToString()
        {
            return "Cmd_motor_pwmMsg: " +
            "\nheader: " + header.ToString() +
            "\nmotor_1_enable: " + motor_1_enable.ToString() +
            "\npwm_motor_1: " + pwm_motor_1.ToString() +
            "\nbaseoffset_1: " + baseoffset_1.ToString() +
            "\nmotor_2_enable: " + motor_2_enable.ToString() +
            "\npwm_motor_2: " + pwm_motor_2.ToString() +
            "\nbaseoffset_2: " + baseoffset_2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
