//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class Pid_debugMsg : Message
    {
        public const string k_RosMessageName = "tb_msgs/pid_debug";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public sbyte pid_id;
        public double feedback;
        public double output;
        public double output_p;
        public double output_i;
        public double output_d;
        public double feedforward;
        public double setpoint;

        public Pid_debugMsg()
        {
            this.header = new HeaderMsg();
            this.pid_id = 0;
            this.feedback = 0.0;
            this.output = 0.0;
            this.output_p = 0.0;
            this.output_i = 0.0;
            this.output_d = 0.0;
            this.feedforward = 0.0;
            this.setpoint = 0.0;
        }

        public Pid_debugMsg(HeaderMsg header, sbyte pid_id, double feedback, double output, double output_p, double output_i, double output_d, double feedforward, double setpoint)
        {
            this.header = header;
            this.pid_id = pid_id;
            this.feedback = feedback;
            this.output = output;
            this.output_p = output_p;
            this.output_i = output_i;
            this.output_d = output_d;
            this.feedforward = feedforward;
            this.setpoint = setpoint;
        }

        public static Pid_debugMsg Deserialize(MessageDeserializer deserializer) => new Pid_debugMsg(deserializer);

        private Pid_debugMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.pid_id);
            deserializer.Read(out this.feedback);
            deserializer.Read(out this.output);
            deserializer.Read(out this.output_p);
            deserializer.Read(out this.output_i);
            deserializer.Read(out this.output_d);
            deserializer.Read(out this.feedforward);
            deserializer.Read(out this.setpoint);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.pid_id);
            serializer.Write(this.feedback);
            serializer.Write(this.output);
            serializer.Write(this.output_p);
            serializer.Write(this.output_i);
            serializer.Write(this.output_d);
            serializer.Write(this.feedforward);
            serializer.Write(this.setpoint);
        }

        public override string ToString()
        {
            return "Pid_debugMsg: " +
            "\nheader: " + header.ToString() +
            "\npid_id: " + pid_id.ToString() +
            "\nfeedback: " + feedback.ToString() +
            "\noutput: " + output.ToString() +
            "\noutput_p: " + output_p.ToString() +
            "\noutput_i: " + output_i.ToString() +
            "\noutput_d: " + output_d.ToString() +
            "\nfeedforward: " + feedforward.ToString() +
            "\nsetpoint: " + setpoint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
