//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class Autodock_statusMsg : Message
    {
        public const string k_RosMessageName = "tb_msgs/autodock_status";
        public override string RosMessageName => k_RosMessageName;

        public ushort status;
        //  0 - idle, 1 - started, 2 - waypoint1sent, 3 - wp1w, 4 - wp2s, 5 - wp2w, 6 - wp3s, 7 - wp3w, 8 - wp4s, 9 - wp4w, 10 - done
        public byte result;
        //  0 - failed, 1 - succeeded, 2 - unknown

        public Autodock_statusMsg()
        {
            this.status = 0;
            this.result = 0;
        }

        public Autodock_statusMsg(ushort status, byte result)
        {
            this.status = status;
            this.result = result;
        }

        public static Autodock_statusMsg Deserialize(MessageDeserializer deserializer) => new Autodock_statusMsg(deserializer);

        private Autodock_statusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "Autodock_statusMsg: " +
            "\nstatus: " + status.ToString() +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
