//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class Pose_controller_debugMsg : Message
    {
        public const string k_RosMessageName = "tb_msgs/pose_controller_debug";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public double current_x;
        public double current_y;
        public double current_yaw;
        public double goal_x;
        public double goal_y;
        public double goal_yaw;
        public double yaw_goalFrame;
        public double direct_goalFrame;
        public double e_d;
        public double e_dir2goal;
        public double e_yaw_poseFrame;
        public double dir2goal_term;
        public double yaw_term;
        public double linear_vel;
        public double angular_vel;
        public double delta_x_goalFrame;
        public double delta_y_goalFrame;

        public Pose_controller_debugMsg()
        {
            this.header = new HeaderMsg();
            this.current_x = 0.0;
            this.current_y = 0.0;
            this.current_yaw = 0.0;
            this.goal_x = 0.0;
            this.goal_y = 0.0;
            this.goal_yaw = 0.0;
            this.yaw_goalFrame = 0.0;
            this.direct_goalFrame = 0.0;
            this.e_d = 0.0;
            this.e_dir2goal = 0.0;
            this.e_yaw_poseFrame = 0.0;
            this.dir2goal_term = 0.0;
            this.yaw_term = 0.0;
            this.linear_vel = 0.0;
            this.angular_vel = 0.0;
            this.delta_x_goalFrame = 0.0;
            this.delta_y_goalFrame = 0.0;
        }

        public Pose_controller_debugMsg(HeaderMsg header, double current_x, double current_y, double current_yaw, double goal_x, double goal_y, double goal_yaw, double yaw_goalFrame, double direct_goalFrame, double e_d, double e_dir2goal, double e_yaw_poseFrame, double dir2goal_term, double yaw_term, double linear_vel, double angular_vel, double delta_x_goalFrame, double delta_y_goalFrame)
        {
            this.header = header;
            this.current_x = current_x;
            this.current_y = current_y;
            this.current_yaw = current_yaw;
            this.goal_x = goal_x;
            this.goal_y = goal_y;
            this.goal_yaw = goal_yaw;
            this.yaw_goalFrame = yaw_goalFrame;
            this.direct_goalFrame = direct_goalFrame;
            this.e_d = e_d;
            this.e_dir2goal = e_dir2goal;
            this.e_yaw_poseFrame = e_yaw_poseFrame;
            this.dir2goal_term = dir2goal_term;
            this.yaw_term = yaw_term;
            this.linear_vel = linear_vel;
            this.angular_vel = angular_vel;
            this.delta_x_goalFrame = delta_x_goalFrame;
            this.delta_y_goalFrame = delta_y_goalFrame;
        }

        public static Pose_controller_debugMsg Deserialize(MessageDeserializer deserializer) => new Pose_controller_debugMsg(deserializer);

        private Pose_controller_debugMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.current_x);
            deserializer.Read(out this.current_y);
            deserializer.Read(out this.current_yaw);
            deserializer.Read(out this.goal_x);
            deserializer.Read(out this.goal_y);
            deserializer.Read(out this.goal_yaw);
            deserializer.Read(out this.yaw_goalFrame);
            deserializer.Read(out this.direct_goalFrame);
            deserializer.Read(out this.e_d);
            deserializer.Read(out this.e_dir2goal);
            deserializer.Read(out this.e_yaw_poseFrame);
            deserializer.Read(out this.dir2goal_term);
            deserializer.Read(out this.yaw_term);
            deserializer.Read(out this.linear_vel);
            deserializer.Read(out this.angular_vel);
            deserializer.Read(out this.delta_x_goalFrame);
            deserializer.Read(out this.delta_y_goalFrame);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.current_x);
            serializer.Write(this.current_y);
            serializer.Write(this.current_yaw);
            serializer.Write(this.goal_x);
            serializer.Write(this.goal_y);
            serializer.Write(this.goal_yaw);
            serializer.Write(this.yaw_goalFrame);
            serializer.Write(this.direct_goalFrame);
            serializer.Write(this.e_d);
            serializer.Write(this.e_dir2goal);
            serializer.Write(this.e_yaw_poseFrame);
            serializer.Write(this.dir2goal_term);
            serializer.Write(this.yaw_term);
            serializer.Write(this.linear_vel);
            serializer.Write(this.angular_vel);
            serializer.Write(this.delta_x_goalFrame);
            serializer.Write(this.delta_y_goalFrame);
        }

        public override string ToString()
        {
            return "Pose_controller_debugMsg: " +
            "\nheader: " + header.ToString() +
            "\ncurrent_x: " + current_x.ToString() +
            "\ncurrent_y: " + current_y.ToString() +
            "\ncurrent_yaw: " + current_yaw.ToString() +
            "\ngoal_x: " + goal_x.ToString() +
            "\ngoal_y: " + goal_y.ToString() +
            "\ngoal_yaw: " + goal_yaw.ToString() +
            "\nyaw_goalFrame: " + yaw_goalFrame.ToString() +
            "\ndirect_goalFrame: " + direct_goalFrame.ToString() +
            "\ne_d: " + e_d.ToString() +
            "\ne_dir2goal: " + e_dir2goal.ToString() +
            "\ne_yaw_poseFrame: " + e_yaw_poseFrame.ToString() +
            "\ndir2goal_term: " + dir2goal_term.ToString() +
            "\nyaw_term: " + yaw_term.ToString() +
            "\nlinear_vel: " + linear_vel.ToString() +
            "\nangular_vel: " + angular_vel.ToString() +
            "\ndelta_x_goalFrame: " + delta_x_goalFrame.ToString() +
            "\ndelta_y_goalFrame: " + delta_y_goalFrame.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
