//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class Servo_positionMsg : Message
    {
        public const string k_RosMessageName = "tb_msgs/servo_position";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public ushort servo_pos_raw;
        // 0-1023
        public double servo_pos_rad;
        public double servo_pos_rad_cmd;
        // torque control mode:
        // kBreak = 0,
        // kOn = 1,
        // kFree = 2
        public byte torque_cmd;

        public Servo_positionMsg()
        {
            this.header = new HeaderMsg();
            this.servo_pos_raw = 0;
            this.servo_pos_rad = 0.0;
            this.servo_pos_rad_cmd = 0.0;
            this.torque_cmd = 0;
        }

        public Servo_positionMsg(HeaderMsg header, ushort servo_pos_raw, double servo_pos_rad, double servo_pos_rad_cmd, byte torque_cmd)
        {
            this.header = header;
            this.servo_pos_raw = servo_pos_raw;
            this.servo_pos_rad = servo_pos_rad;
            this.servo_pos_rad_cmd = servo_pos_rad_cmd;
            this.torque_cmd = torque_cmd;
        }

        public static Servo_positionMsg Deserialize(MessageDeserializer deserializer) => new Servo_positionMsg(deserializer);

        private Servo_positionMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.servo_pos_raw);
            deserializer.Read(out this.servo_pos_rad);
            deserializer.Read(out this.servo_pos_rad_cmd);
            deserializer.Read(out this.torque_cmd);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.servo_pos_raw);
            serializer.Write(this.servo_pos_rad);
            serializer.Write(this.servo_pos_rad_cmd);
            serializer.Write(this.torque_cmd);
        }

        public override string ToString()
        {
            return "Servo_positionMsg: " +
            "\nheader: " + header.ToString() +
            "\nservo_pos_raw: " + servo_pos_raw.ToString() +
            "\nservo_pos_rad: " + servo_pos_rad.ToString() +
            "\nservo_pos_rad_cmd: " + servo_pos_rad_cmd.ToString() +
            "\ntorque_cmd: " + torque_cmd.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
