//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class Tbcore_statusMsg : Message
    {
        public const string k_RosMessageName = "tb_msgs/tbcore_status";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public ushort voltage_cell_1;
        public ushort voltage_cell_2;
        public ushort voltage_cell_3;
        public ushort voltage_cell_4;
        public ushort voltage_cell_5;
        public short charging_current;
        public byte docked_status;
        public byte fet_status;
        public byte status_1;
        public byte status_2;
        public byte status_3;
        public byte status_4;

        public Tbcore_statusMsg()
        {
            this.header = new HeaderMsg();
            this.voltage_cell_1 = 0;
            this.voltage_cell_2 = 0;
            this.voltage_cell_3 = 0;
            this.voltage_cell_4 = 0;
            this.voltage_cell_5 = 0;
            this.charging_current = 0;
            this.docked_status = 0;
            this.fet_status = 0;
            this.status_1 = 0;
            this.status_2 = 0;
            this.status_3 = 0;
            this.status_4 = 0;
        }

        public Tbcore_statusMsg(HeaderMsg header, ushort voltage_cell_1, ushort voltage_cell_2, ushort voltage_cell_3, ushort voltage_cell_4, ushort voltage_cell_5, short charging_current, byte docked_status, byte fet_status, byte status_1, byte status_2, byte status_3, byte status_4)
        {
            this.header = header;
            this.voltage_cell_1 = voltage_cell_1;
            this.voltage_cell_2 = voltage_cell_2;
            this.voltage_cell_3 = voltage_cell_3;
            this.voltage_cell_4 = voltage_cell_4;
            this.voltage_cell_5 = voltage_cell_5;
            this.charging_current = charging_current;
            this.docked_status = docked_status;
            this.fet_status = fet_status;
            this.status_1 = status_1;
            this.status_2 = status_2;
            this.status_3 = status_3;
            this.status_4 = status_4;
        }

        public static Tbcore_statusMsg Deserialize(MessageDeserializer deserializer) => new Tbcore_statusMsg(deserializer);

        private Tbcore_statusMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.voltage_cell_1);
            deserializer.Read(out this.voltage_cell_2);
            deserializer.Read(out this.voltage_cell_3);
            deserializer.Read(out this.voltage_cell_4);
            deserializer.Read(out this.voltage_cell_5);
            deserializer.Read(out this.charging_current);
            deserializer.Read(out this.docked_status);
            deserializer.Read(out this.fet_status);
            deserializer.Read(out this.status_1);
            deserializer.Read(out this.status_2);
            deserializer.Read(out this.status_3);
            deserializer.Read(out this.status_4);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.voltage_cell_1);
            serializer.Write(this.voltage_cell_2);
            serializer.Write(this.voltage_cell_3);
            serializer.Write(this.voltage_cell_4);
            serializer.Write(this.voltage_cell_5);
            serializer.Write(this.charging_current);
            serializer.Write(this.docked_status);
            serializer.Write(this.fet_status);
            serializer.Write(this.status_1);
            serializer.Write(this.status_2);
            serializer.Write(this.status_3);
            serializer.Write(this.status_4);
        }

        public override string ToString()
        {
            return "Tbcore_statusMsg: " +
            "\nheader: " + header.ToString() +
            "\nvoltage_cell_1: " + voltage_cell_1.ToString() +
            "\nvoltage_cell_2: " + voltage_cell_2.ToString() +
            "\nvoltage_cell_3: " + voltage_cell_3.ToString() +
            "\nvoltage_cell_4: " + voltage_cell_4.ToString() +
            "\nvoltage_cell_5: " + voltage_cell_5.ToString() +
            "\ncharging_current: " + charging_current.ToString() +
            "\ndocked_status: " + docked_status.ToString() +
            "\nfet_status: " + fet_status.ToString() +
            "\nstatus_1: " + status_1.ToString() +
            "\nstatus_2: " + status_2.ToString() +
            "\nstatus_3: " + status_3.ToString() +
            "\nstatus_4: " + status_4.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
