//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class Wheel_encoderMsg : Message
    {
        public const string k_RosMessageName = "tb_msgs/wheel_encoder";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public double motor_left_vel;
        public double motor_right_vel;
        public int motor_left_accel;
        public int motor_right_accel;
        public int motor_left_pos;
        public int motor_right_pos;

        public Wheel_encoderMsg()
        {
            this.header = new HeaderMsg();
            this.motor_left_vel = 0.0;
            this.motor_right_vel = 0.0;
            this.motor_left_accel = 0;
            this.motor_right_accel = 0;
            this.motor_left_pos = 0;
            this.motor_right_pos = 0;
        }

        public Wheel_encoderMsg(HeaderMsg header, double motor_left_vel, double motor_right_vel, int motor_left_accel, int motor_right_accel, int motor_left_pos, int motor_right_pos)
        {
            this.header = header;
            this.motor_left_vel = motor_left_vel;
            this.motor_right_vel = motor_right_vel;
            this.motor_left_accel = motor_left_accel;
            this.motor_right_accel = motor_right_accel;
            this.motor_left_pos = motor_left_pos;
            this.motor_right_pos = motor_right_pos;
        }

        public static Wheel_encoderMsg Deserialize(MessageDeserializer deserializer) => new Wheel_encoderMsg(deserializer);

        private Wheel_encoderMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.motor_left_vel);
            deserializer.Read(out this.motor_right_vel);
            deserializer.Read(out this.motor_left_accel);
            deserializer.Read(out this.motor_right_accel);
            deserializer.Read(out this.motor_left_pos);
            deserializer.Read(out this.motor_right_pos);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.motor_left_vel);
            serializer.Write(this.motor_right_vel);
            serializer.Write(this.motor_left_accel);
            serializer.Write(this.motor_right_accel);
            serializer.Write(this.motor_left_pos);
            serializer.Write(this.motor_right_pos);
        }

        public override string ToString()
        {
            return "Wheel_encoderMsg: " +
            "\nheader: " + header.ToString() +
            "\nmotor_left_vel: " + motor_left_vel.ToString() +
            "\nmotor_right_vel: " + motor_right_vel.ToString() +
            "\nmotor_left_accel: " + motor_left_accel.ToString() +
            "\nmotor_right_accel: " + motor_right_accel.ToString() +
            "\nmotor_left_pos: " + motor_left_pos.ToString() +
            "\nmotor_right_pos: " + motor_right_pos.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
