//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class GotoPoseFeedback : Message
    {
        public const string k_RosMessageName = "tb_msgs/GotoPose";
        public override string RosMessageName => k_RosMessageName;

        // feedback
        public Geometry.PoseStampedMsg baseLink_pose;

        public GotoPoseFeedback()
        {
            this.baseLink_pose = new Geometry.PoseStampedMsg();
        }

        public GotoPoseFeedback(Geometry.PoseStampedMsg baseLink_pose)
        {
            this.baseLink_pose = baseLink_pose;
        }

        public static GotoPoseFeedback Deserialize(MessageDeserializer deserializer) => new GotoPoseFeedback(deserializer);

        private GotoPoseFeedback(MessageDeserializer deserializer)
        {
            this.baseLink_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.baseLink_pose);
        }

        public override string ToString()
        {
            return "GotoPoseFeedback: " +
            "\nbaseLink_pose: " + baseLink_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
