//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tb
{
    [Serializable]
    public class GotoPoseGoal : Message
    {
        public const string k_RosMessageName = "tb_msgs/GotoPose";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public Geometry.PoseWithCovarianceStampedMsg goal_pose;

        public GotoPoseGoal()
        {
            this.goal_pose = new Geometry.PoseWithCovarianceStampedMsg();
        }

        public GotoPoseGoal(Geometry.PoseWithCovarianceStampedMsg goal_pose)
        {
            this.goal_pose = goal_pose;
        }

        public static GotoPoseGoal Deserialize(MessageDeserializer deserializer) => new GotoPoseGoal(deserializer);

        private GotoPoseGoal(MessageDeserializer deserializer)
        {
            this.goal_pose = Geometry.PoseWithCovarianceStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goal_pose);
        }

        public override string ToString()
        {
            return "GotoPoseGoal: " +
            "\ngoal_pose: " + goal_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
